// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZEIyI4mRmlQ6npYkQyPXfj5UcC2o6RBA',
    appId: '1:961787081371:web:d88a3b3bafdd1ce43dcc3e',
    messagingSenderId: '961787081371',
    projectId: 'todoapp-85846',
    authDomain: 'todoapp-85846.firebaseapp.com',
    storageBucket: 'todoapp-85846.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTNtT0Nh9vem4Mn_ki70aEK4RTo-RoHJ0',
    appId: '1:961787081371:android:e2b41f14ec0f7b523dcc3e',
    messagingSenderId: '961787081371',
    projectId: 'todoapp-85846',
    storageBucket: 'todoapp-85846.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkRssIGoF4jw-lnhdwnGqehH0Lq2XGnpY',
    appId: '1:961787081371:ios:290f5ec5f5a4a9163dcc3e',
    messagingSenderId: '961787081371',
    projectId: 'todoapp-85846',
    storageBucket: 'todoapp-85846.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkRssIGoF4jw-lnhdwnGqehH0Lq2XGnpY',
    appId: '1:961787081371:ios:290f5ec5f5a4a9163dcc3e',
    messagingSenderId: '961787081371',
    projectId: 'todoapp-85846',
    storageBucket: 'todoapp-85846.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZEIyI4mRmlQ6npYkQyPXfj5UcC2o6RBA',
    appId: '1:961787081371:web:ad0032d4a74f3a623dcc3e',
    messagingSenderId: '961787081371',
    projectId: 'todoapp-85846',
    authDomain: 'todoapp-85846.firebaseapp.com',
    storageBucket: 'todoapp-85846.appspot.com',
  );
}
